language: scala
scala:
- 2.10.1
jdk:
- oraclejdk7
before_script:
- psql -U postgres -c "CREATE USER enricher WITH password 'supersecret1';"
- psql -U postgres -c "CREATE DATABASE sql_enrichment_test WITH OWNER = enricher;"
- psql -U postgres -d sql_enrichment_test < integration-tests/sql-enrichment-test.sql
- psql -U postgres -d sql_enrichment_test -c "GRANT ALL ON enrichment_test TO enricher;"
script:
- python integration-tests/api-lookup-test.py &
- cd 3-enrich/scala-common-enrich
- cd ../..
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
addons:
  postgresql: '9.3'
services:
- postgresql
before_deploy:
- pip install --user release-manager==0.2.0
deploy:
- provider: script
  script: ./.travis/deploy_kinesis.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_kinesis_release_tag.sh $TRAVIS_TAG)" == "" && $? ==
      0'
- provider: script
  script: ./.travis/deploy_hadoop_enrich.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_hadoop_enrich_release_tag.sh $TRAVIS_TAG)" == "" &&
      $? == 0'
- provider: script
  script: ./.travis/deploy_hadoop_shred.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_hadoop_shred_release_tag.sh $TRAVIS_TAG)" == "" && $?
      == 0'
- provider: script
  script: ./.travis/deploy_hadoop_enrich.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_hadoop_event_recovery_release_tag.sh $TRAVIS_TAG)" ==
      "" && $? == 0'
- provider: script
  script: ./.travis/deploy_emr.sh $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(.travis/is_emr_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
env:
  global:
  - secure: J5k7QA2SySQVZAgxuGRawaDRIzLyl8MlZN7R39YVCP05RwGrvdzsXQ4V7WcMXcV8JZC9RNAjwMpLj/5GT6p5c0JeBy34CGHuZMmTRQEyfXkVl1JW0xNXOsNsHMYZUki/xlTKx0j//bsiChwR09YrE+eBLtzW3jlUWpu3atZrPLHqx03LJU7Wy8WTNVLMTn1c1IF70BUbXCpjvxfTz1LNROEm5aIqs4dzB5Sa8SktuLWc7AanZaohLeMXTpGj/Z2QfcL0Bi8zJ9IpNf8EXHa24k0Y9CIzM7vpSklInuAhUYDUb0RzDmbF88SbHTn35qPs8+LhBSlnL4DDTLS07vLYnIyV3hTe5rkx7a+6E1E+C3/4S5x2u68J9Bd4y0P19k0mIMJghXAJ+rgY5BqXt0pgZecII9PkM7obQQhXS9sNONfVM9blx3d+OCfS+nPpLCUGs+4sGRa+phL5ssA85n8g/+JwkJd7U9ELi5QYxvbg4EyAMPNV2zZEgAVgkJtC6Iv+72ttEyVBNEyOzVoT8I9lJKw5Vhy/jKvpLQUT4kN1V80fjMYPxZJZvl99o3mERsOp1WN2CQFd/9I70LZeNLbEZK1Uet2lLBs3RXwwElhqPbFuWhLJMIaQ7DgnktTlnorfEwPT/jdcS/FB5sas6KxIiII361qiD0fDQvmL/vzhwig=
  - secure: f6of2k/Vq56suV/p3gEA0+mDL0PsGKi1o/PhjmnLF4hb4yP3tLG+plfPQJyHbkykQqwjM7zBe1IKpssQflu+h+WE0AiKl07d5hp0aLVHn5K0sv+7FUasNiPDXdpW50aKQlxwu6fSpvLkfemJhwn9gtAtNo1nRy0zml27qaomBQahJxUqT7Y9QxMYb0TvE/14NrpOBe9lfNE3kci7YnzhjHZwHnoq7mxBg5YLkBe6fhTqcvX+Cp9WjO3JAOjE9d+jZsSzYG3I6NKyhflnx+aLbFkO/uhGxvjVo9IoHiT9DopALYld3oJTzVSfy3iM5f8SrR+Vm3V20k4cToXJ7c0ZTOibsJdAFQ1kUHbLB+EzXV5vbaZ5P4s9bF2Yn6ECIRFmyFqtO+eTKAY/AcoA4GSBom94Cv8zPR3RsZHOLm8ySNQ+iSDJHTYkNf78pTWa/ZwFhYivgxZvKHkVNj/rHhn1jbxEfsmqWEHgvNXmNYQbcNWQcS0oxk/SsKSPk7gsLZRGV/+TRByKB2FSkiReUDqCOAi6wdV8Z0rnaKDLSMNHPB+Mk7ZT2Nemw78jvEUm4fdLjLkFo6iqirzeagbjOuMMYE03NdMmd0XUQV5PDtf19UDRR542K4w7OhiTK1w4xDDlem6EtPQdiyol6uCMLm++8Jt76GSQkxccyUWHq1mXEjE=
